### ISSUE TITLE
Question about Kbuild?

### ISSUE THREAD

**Issue by rathnavels** [xpdu/gcov-kernel-exercise#1]
Hello,

I can see you have a Kbuild file.   Do you mean to say the contents of which needs to be added to kernel Kbuild ?

**Comment by xpdu** [comment]
Hi @rathnavels, thanks for asking! However, could you clarify this part: "needs to be added to kernel Kbuild"?

In a nutshell, Kbuild files are Makefiles in the Linux kernel, i.e. used to declare targets and additional build options. They don't imply any changes in the Linux kernel git tree for the "out of tree" modules like this. When you type "make", it reads the Makefile, goes to the kernel tree, engages the Kbuild infrastructure; then Kbuild goes back to the module, reads the Kbuild file, and finally builds a module (.ko) file.

More about Kbuild for modules: https://www.kernel.org/doc/html/latest/kbuild/modules.html.

Hope that helps?

**Comment by rathnavels** [comment]
Hello @xpdu,

Thanks a lot! It helps.  I didn't know that Kbuild file works in tandem with Makefile. It makes sense now.  

I ran your code and the module load and unload is working fine.  I see a *.gcda file and a sym link to *.gcno file in sys/kernel/debug/gcov/$(PWD).. Yet, the *.gcda file has no information when doing gcov to extract coverage info.  Can you please tell me if I'm missing something.

FYI, I'm cross compiling this on an ARM target, so my build and target machines are different.  Any advice is greatly appreciate!

**Comment by rathnavels** [comment]
Just as an additional info, I'm able to generate proper .gcda files when I run user space app, and get coverage info as well on the target machine I mentioned about.  Shouldn't I get a *.gcda file that will be usable with gcov to get coverage for the driver code?

**Comment by xpdu** [comment]
Hi @rathnavels, I'm glad you're getting the *.gcda files generated, it means that instrumentation generally works!

A quick guess is that runtime libraries in your test machine are older than in a build machine, is it the case?

AFAIR, the outcome depends on the version of the gcov tool you're using. For example, if you're trying to generate the *.gcov reports on a target machine with an _older_ gcov/gcc version, it might refuse to do so due to backward incompatibility. In my memory, sometimes gcov had hard times decoding the *.gcda and *.gcno files and even crashed on a _test_ machine similarly to https://stackoverflow.com/questions/29123940/segmentation-fault-with-gcov, so in the end, I've decided to fetch all the *.gcda files back to the build machine and generate the coverage reports there.

At the same time, the architecture/cross-compilation wasn't an issue. However, I might be wrong!

**Comment by rathnavels** [comment]
Hello Mate,

Firstly really thanks for taking your time and responding to my queries.  I really appreciate it.

I am indeed aware of version mismatch issues which I faced earlier but that isn't stopping the show for user space apps.  Even though different versions of gcov are throwing warnings, it still generates the coverage info(for user space apps only). So I doubt my issue would have to do with version mismatch.

Can you just confirm if you are doing the same steps?
- Building -->  insmod  --> rmmod -->  After this .gcda files are getting generated in debugfs?  And those .gcda files are fat and healthy (I mean it has some info)?

**Comment by rathnavels** [comment]
To activate gcov, which flags did you set on the Kernel?  And you built your kernel freshly before getting coverage?

**Comment by rathnavels** [comment]
I got it working mate. The problem was with the gcov version that I was using. Replaced just the kernel/gcov folder from a recent linux kernel and it worked! Thanks for your help :)
